# Generated by Django 5.0 on 2024-01-04 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to='content_previews/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to='content_previews/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('is_free', models.BooleanField()),
                ('category', models.CharField(choices=[('Art', 'Art'), ('Music', 'Music'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Literature', 'Literature'), ('Not_selected', 'Not selected')], default='Not_selected')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
