# Generated by Django 5.0 on 2024-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="collection_previews/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.TextField()),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="content_previews/"
                    ),
                ),
                ("post_time", models.DateTimeField(auto_now_add=True)),
                ("is_free", models.BooleanField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Art", "Art"),
                            ("Poems", "Poems"),
                            ("Education", "Education"),
                            ("Entertainment", "Entertainment"),
                            ("Not_selected", "Not selected"),
                        ],
                        default="Not selected",
                    ),
                ),
            ],
        ),
    ]
