# Generated by Django 5.0 on 2024-01-05 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="album",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
    ]
